import React, { useState } from 'react';
import { Notice, Input } from 'components';
import { calculateResult } from 'math/egyptian_lands';
import { GameResult } from './components/GameResult';

interface Props {
  game: string;
}
export const EgyptianLands = ({ game }: Props) => {
  const [clientSeed, setClientSeed] = useState('');
  const [serverSeed, setServerSeed] = useState('');
  const [nonce, setNonce] = useState('');
  const [result, setResult] = useState<any>(null);

  const onCalculate = () => {
    setResult(calculateResult(serverSeed, clientSeed, nonce));
  };

  return (
    <div>
      <Notice />
      <div className="inputsRow">
        <Input
          title="Client Seed"
          subTitle="Client Seed comes from your browser and is never generated by the server."
          value={clientSeed}
          onChange={({ target }) => setClientSeed(target.value)}
        />
        <Input
          title="Server Seed"
          subTitle="Server Seed is generated by the server. It is only shared with you after you rotate the seed."
          value={serverSeed}
          onChange={({ target }) => setServerSeed(target.value)}
        />

        <Input
          title="Nonce"
          subTitle="Nonce starts from 1 and is a count for the games you play (associated to the particular server seed)."
          value={nonce}
          onChange={({ target }) => setNonce(target.value)}
        />
      </div>
      <button type="button" className="btn btn-info" onClick={onCalculate}>
        Calculate
      </button>
      {result && <GameResult game_id={game} steps={result.steps} />}
    </div>
  );
};
