import React, { useState } from 'react';
import { Notice, Input, Select } from 'components';
import { GameResult } from './components/GameResult';
import { calculateResult } from 'math/aztec_temple';

interface Props {
  game: string;
}

const super_symbols = [
  { sbl: null, label: 'Base game' },
  { sbl: 'H1' },
  { sbl: 'H2' },
  { sbl: 'H3' },
  { sbl: 'H4' },
  { sbl: 'N1' },
  { sbl: 'N2' },
  { sbl: 'N3' },
  { sbl: 'N4' },
  { sbl: 'N5' },
];

export const AztecTemple = ({ game }: Props) => {
  const [clientSeed, setClientSeed] = useState('');
  const [serverSeed, setServerSeed] = useState('');
  const [nonce, setNonce] = useState('');
  const [super_sbl, setSuperSbl] = useState<any>(super_symbols[0]);
  const [result, setResult] = useState<any>(null);

  const onClick = () => {
    setResult(calculateResult(serverSeed, clientSeed, nonce, super_sbl.sbl));
  };

  return (
    <div>
      <Notice />
      <div className="inputsRow">
        <Input
          title="Client Seed"
          subTitle="Client Seed comes from your browser and is never generated by the server."
          value={clientSeed}
          onChange={({ target }) => setClientSeed(target.value)}
        />
        <Input
          title="Server Seed"
          subTitle="Server Seed is generated by the server. It is only shared with you after you rotate the seed."
          value={serverSeed}
          onChange={({ target }) => setServerSeed(target.value)}
        />

        <Input
          title="Nonce"
          subTitle="Nonce starts from 1 and is a count for the games you play (associated to the particular server seed)."
          value={nonce}
          onChange={({ target }) => setNonce(target.value)}
        />

        <Select
          game={game}
          title="Free symbol"
          value={super_sbl}
          subTitle="Select it only if need calcutalate free spin result"
          options={super_symbols}
          onChange={(val) => setSuperSbl(val)}
        />
      </div>
      <button type="button" className="btn btn-info" onClick={onClick}>
        Calculate
      </button>
      {result && <GameResult game_id={game} {...result} />}
    </div>
  );
};
