import React, { useState } from 'react';
import { Input, Notice, Switch } from 'components';
import { NudgeSelect, GameResult } from './components';
import { calculateResult } from 'math/shooting_range';

interface Props {
  game: string;
}

export const ShootingRange = ({ game }: Props) => {
  const [clientSeed, setClientSeed] = useState('');
  const [serverSeed, setServerSeed] = useState('');
  const [nonce, setNonce] = useState('');
  const [isExtraBet, setIsExtraBet] = useState<boolean>(false);
  const [mask, setMask] = useState<number[]>([0, 0, 0, 0, 0, 0]);
  const [result, setResult] = useState<any>(null);

  const onCalculate = () => {
    setResult(calculateResult(serverSeed, clientSeed, nonce, mask, isExtraBet));
  };

  return (
    <div>
      <Notice />
      <div className="inputsRow">
        <Input
          title="Client Seed"
          subTitle="Client Seed comes from your browser and is never generated by the server."
          value={clientSeed}
          onChange={({ target }) => setClientSeed(target.value)}
        />
        <Input
          title="Server Seed"
          subTitle="Server Seed is generated by the server. It is only shared with you after you rotate the seed."
          value={serverSeed}
          onChange={({ target }) => setServerSeed(target.value)}
        />
        <Input
          title="Nonce"
          subTitle="Nonce starts from 1 and is a count for the games you play (associated to the particular server seed)."
          value={nonce}
          onChange={({ target }) => setNonce(target.value)}
        />
        <Switch
          checked={isExtraBet}
          onChange={() => setIsExtraBet(!isExtraBet)}
          title="Basilisk bet"
          subTitle="An activated feature in the game settings, it can affect the outcome of the game"
        />
        <NudgeSelect onSelect={(mask) => setMask(mask)} title={'Nudge symbols positions'} />
      </div>
      <button type="button" className="btn btn-info" onClick={onCalculate}>
        Calculate
      </button>
      {result && <GameResult game={game} {...result} />}
    </div>
  );
};
